### ISSUE TITLE
Launch tracking

### ISSUE THREAD

**Issue by kytrinyx** [exercism/vlang#1]
This issue helps keep track of the tasks you're working on towards launching this track.

The next steps are:

- [ ] [Join our community](https://exercism.org/docs/building/tracks/new/join-our-community)
- [ ] [Select programming language variant](https://exercism.org/docs/building/tracks/new/select-programming-language-variant) (if applicable)
- [ ] [Select testing framework](https://exercism.org/docs/building/tracks/new/select-testing-framework)
- [ ] [Add the first exercise](https://exercism.org/docs/building/tracks/new/add-first-exercise)
- [ ] [Add initial exercises](https://exercism.org/docs/building/tracks/new/add-initial-exercises)
- [ ] [Setup Continuous Integration](https://exercism.org/docs/building/tracks/new/setup-continuous-integration)
- [ ] [Prepare for launch](https://exercism.org/docs/building/tracks/new/prepare-for-launch)
- [ ] [Find Maintainers](https://exercism.org/docs/building/tracks/new/find-maintainers)
- [ ] [Launch!](https://exercism.org/docs/building/tracks/new/launch)
- [ ] [Implement tooling](https://exercism.org/docs/building/tracks/new/implement-tooling)
- [ ] [Prepare for open source contributions from strangers](https://exercism.org/docs/building/tracks/new/prepare-for-contributions)

Once you've finished a task, you can check them in this list.

## Questions

Please ask if you have any questions or if anything is confusing!

**Comment by 1ethanhansen** [comment]
@cindRoberta are you still working on this? is there something I can do to help? I'm a vlang fan and would love to see it on exercism!

**Comment by cindRoberta** [comment]
@1ethanhansen no, I'm using Rust now

**Comment by iHiD** [comment]
@1ethanhansen Would you like to take over building this track?

**Comment by 1ethanhansen** [comment]
> @1ethanhansen Would you like to take over building this track?

@iHiD that depends... looks like there was a conflict with how exercism names exercises and module names in vlang. That's coming from [a previous attempt](https://github.com/petertseng/exercism-v#readme). Also https://github.com/exercism/request-new-language-track/issues/74

So it depends on if there's a good resolution to that. I honestly don't have a ton of technical experience or a ton of time to devote to this - maybe a couple hours a week tops. I'd love to see V included, but not sure if I have the skills or bandwidth to accomplish it!

**Comment by iHiD** [comment]
Point 3 seems like a reasonable solution to me in the issue you linked 🙂

**Comment by 1ethanhansen** [comment]
Well in that case yeah I'd be happy to build this track!

**Comment by iHiD** [comment]
They are :) @ErikSchierboom and @jonathandmiddleton can help get you started on the technical and community sides. If you send an email to erik@exercism.org and jonathan@exercism.org they can spend 30mins going through things with you :)

**Comment by kytrinyx** [comment]
@1ethanhansen Would you like to be given write-access to this repository? I know you said that you're not going to be spending a ton of time on it, but it sounds like at the moment you're what this track has :)

**Comment by 1ethanhansen** [comment]
@kytrinyx I would love write access! Hopefully I'll have more time to finish it/work on it around Christmas time/new years

**Comment by kytrinyx** [comment]
Lovely! I'll send you an invite now.

**Comment by 1ethanhansen** [comment]
@kytrinyx got the invite!! thank you!

**Comment by kytrinyx** [comment]
If you feel lonely and want to chat about how to proceed with various things, feel free to holler in the forum: https://forum.exercism.org/c/exercism/building-exercism/125

**Comment by 1ethanhansen** [comment]
@kytrinyx it seems i still don't have write access. I'm unable to merge in https://github.com/exercism/vlang/pull/13 which I think I [should be able to do with write access](https://docs.github.com/en/organizations/managing-user-access-to-your-organizations-repositories/repository-roles-for-an-organization#permissions-for-each-role)

**Comment by kytrinyx** [comment]
@1ethanhansen Sorry about that, and thanks for the heads up! It should now be sorted.

**Comment by 1ethanhansen** [comment]
@kytrinyx thank you! i've got access now :)

**Comment by 1ethanhansen** [comment]
Closed by #39 :partying_face:
