### ISSUE TITLE
Add List Ops exercise

### ISSUE THREAD

**Issue by m-charlton** [exercism/vlang#144]
Port the [List Ops](https://github.com/exercism/problem-specifications/tree/main/exercises/list-ops) exercise to V

Assign to @m-charlton

**Comment by m-charlton** [comment]
### Blocker: unable to implement `concat` function

The [problem description](https://github.com/exercism/problem-specifications/blob/main/exercises/list-ops/canonical-data.json) for the list-ops exercise specifies the following test data:

```vlang
    input := [[1, 2], [3], [], [4, 5, 6]] // type: [][]int{}
    expected := [1, 2, 3, 4, 5, 6]        // type: []int{}
```

This would require `concat` to have a signature of:

```vlang
    fn concat[T](array [][]T) []T
```

Another test case:

```vlang
    input := [[[1], [2]], [[3]], [[]], [[4, 5, 6]]] // type: [][][]int{}
    expected =: [[1], [2], [3], [], [4, 5, 6]]      // type: [][]int{}
```

Would require a different signature:

```vlang
    fn concat[T](array [][][]T) [][]T
```

As V doesn't support multiple dispatch, it looks as if it's impossible to implement `concat`.

This would also mean that the [flatten-array](https://github.com/exercism/problem-specifications/tree/main/exercises/flatten-array) exercise would suffer the same fate.

**Comment by 1ethanhansen** [comment]
Would this be possible with [generics](https://github.com/vlang/v/blob/master/doc/docs.md#generics)?

**Comment by m-charlton** [comment]
You could be right. As an experiment, I tried the following:

```vlang
module main

fn foo[T](v T) T {
	return v
}

fn main() {
	println(foo[int](7)) // -> 7
	println(foo[[]int]([1,2,3])) // -> [1, 2, 3]
        println(foo[[][]int]([[1,2,3], [], [5,6]])) // -> [[1, 2, 3], [], [5, 6]]
}
```

I had, incorrectly, assumed that V's generics could not handle this scenario. This requires further investigation. Publishing of the exercise will be delayed, appologies.

**Comment by 1ethanhansen** [comment]
No worries! There's no deadline on all of this :smile:

**Comment by m-charlton** [comment]
### Extra pair of eyes needed

I'd be grateful if you'd look over my [code](https://github.com/exercism/vlang/files/12147807/concat.v.zip) to make sure I'm not doing anything stupid.

`concat()` is on line 5. The generic types are specified by`S` (input) and `T` (output).

`result` is initialised on line 6 and its type tested on line 8. If I call this function, uncomment line 59, I get a runtime error:

```
  error: invalid operation: shift on type '[]int`
```

Did a quick search for the above and found similar problems [here](https://github.com/vlang/v/issues/15470) & [here](https://github.com/vlang/v/discussions/14607).

`concat_explicit_output()` explicitly states the output type and works as expected.

I get runtime panics if I invoke the `insert` method on result. Now, here's the interesting part: If I use the `arrays.concat()` _function_ (see line 40), no runtime error and we get the correct output.

I'm beginning to think that this _could_  be a bug. If a method is called on a generic type, then runtime error. I don't know if, under the hood, the `<<` operator is implemented as a method. However, if the generic type is passed to a function, then it works as expected.

Instead of raising this as a issue, I could raise it as a [discussion](https://github.com/vlang/v/discussions/)

Any thoughts?

Compiler version: 0.4.0 6b29d62

**Comment by 1ethanhansen** [comment]
Huh interesting. One thing to note is that `<<` _does_ do different things depending on what operands it takes in. It can also be used to denote a bitshift, so it's possible that it doesn't work with generic types. I would say start a discussion if you think it could be interesting (feel free to tag me if you do, I'd be interested!), and for now go ahead and just use `arrays.concat`

That's my thoughts, anything there that would be counter-intuitive or that doesn't make sense?

Good work btw, V's insistence on not having undefined behavior makes stuff like this very tricky!

**Comment by m-charlton** [comment]
Kicked of a [discussion](https://github.com/vlang/v/discussions/18965). I don't think I can use [arrays.concat](https://modules.vlang.io/arrays.html#concat) as the array dimensions are fixed.

```vlang
fn concat[T](a []T, b ...T) []T
```

The List-Ops operation needs to be flexible. For example if the input is a 3D array then the output must be a 2D array. `arrays.concat()` can only cope with a 1D array.

Here's where we stand with the list-ops

- [x] `append`
- [ ]  `concat` not implemented, not tested
- [x]  `filter`
- [x]  `length` 
- [ ]  `foldr`  implemented, partialy tested  
- [ ]  `foldl`  implemented, partialy tested  
- [ ]  `reverse` implemented, failing a test.

Hitting the same problem with `reverse` as I've encoutered with `concat` - namely that the dimension of the input array can vary. This is true though of all the functions. Once this problem is resolved then, I need to make all the functions more _generic_.

**Comment by 1ethanhansen** [comment]
Ah sorry I misunderstood what the problem was. For concat the description says it should return a single, flattened array. But that doesn't seem to happen with [this test](https://github.com/exercism/problem-specifications/blob/main/exercises/list-ops/canonical-data.json#L80C22-L80C60). That behavior seems more like V's `array.flatten`. Would it maybe be possible to mostly use `arrays.flatten` and just check for empty arrays?

**Comment by m-charlton** [comment]
Unfortunatly that won't work either as `arrays.flatten` takes as its argument a 2D array and yields a 1D array. Here's what happens when I attempt to pass a 3D array

```
error: cannot use `[][][]int` as `[][]int` in argument 1 to `arrays.flatten`
```

The documentation is somewhat misleading:

> flatten flattens n + 1 dimensional array into n dimensional array

should read:

> flatten flattens a two dimensional (2D) array into a one dimensional (1D) array

I'll issue a PR for that.

To address the other issue of making all functions more _generic_. At present the implementation of `length` is:

```vlang
pub fn length[T](array []T) int {
        return foldl[T, int](array, 0, fn [T](acc int, _ T) int {
                return acc + 1
        })
}
```

This is fine if only dealing with 1D arrays but, not for 2D, 3D, ..., etc. Internally length uses `foldl` so, this must also change.

**Comment by 1ethanhansen** [comment]
Oh darn! Yeah I just read the description. Very misleading

As for making the functions more generic, I've exhausted all of my ideas unfortunately. I've subscribed to the discussion you stated on the V forum, so if anyone has an idea maybe we can circle back to this. Or if you've got another idea, I'm all ears!

**Comment by m-charlton** [comment]
My mistake. `arrays.flatten()` _does_ work with multi-dimensional arrays. Take the following:

```vlang
module main

import arrays { flatten }

fn main() {
	assert flatten[[]int]([[[1, 2]], [[3]], [[4, 5]]]) == [
		[1, 2],
		[3],
		[4, 5],
	]
}
```

I had failed to understand that arrays could be types. Once this was pointed out to me then the list-ops implementation was not too difficult.

I'm in the final stages of putting together a draft PR. There's one testcase that I'd like your input on.
