### ISSUE TITLE
Add Perfect Numbers exercise

### ISSUE THREAD

**Issue by m-charlton** [exercism/vlang#158]
Port the [perfect numbers](https://github.com/exercism/problem-specifications/tree/main/exercises/perfect-numbers) exercise.

Assign to @m-charlton

Had a quick look at the [canonical-data.json](https://github.com/exercism/problem-specifications/blob/main/exercises/perfect-numbers/canonical-data.json). The output can be an error or one of three classes: 'abundant', 'deficient' or 'perfect'. I think this would be a good opportunity to introduce [result types](https://github.com/vlang/v/blob/master/doc/docs.md#optionresult-types-and-error-handling) and [enums](https://github.com/vlang/v/blob/master/doc/docs.md#enums)

**Comment by 1ethanhansen** [comment]
I believe there are already a couple exercises with result types (see below for examples). Can't remember about enums off the top of my head.

- https://github.com/exercism/vlang/blob/b4f4cfaf94efcf1f76c13d1182eb614819badb6a/exercises/practice/affine-cipher/run_test.v#L96
- https://github.com/exercism/vlang/blob/c5f3a169f09af6b062c799bcfb792da35642f6e8/exercises/practice/space-age/run_test.v#L41
- https://github.com/exercism/vlang/blob/b4f4cfaf94efcf1f76c13d1182eb614819badb6a/exercises/practice/collatz-conjecture/run_test.v#L35
