### ISSUE TITLE
Exchange numerator and denominator names in Rational.new arguments

### ISSUE THREAD

**Issue by keiravillekode** [exercism/vlang#181]
The rational-numbers exercise has the test

```
fn test_add_two_positive_rational_numbers() {
	r1 := Rational.new(1, 2)
	r2 := Rational.new(2, 3)

	assert r1.add(r2) == Rational.new(7, 6)
}
```

This is clearly saying that one half plus two thirds is seven sixths. All good.

In `Rational.new` we should call the first argument the [numerator](https://byjus.com/maths/numerator/) and we should call the second argument the [denominator](https://byjus.com/maths/denominator/).

Line 7 of [rational_numbers.v](https://github.com/exercism/vlang/blob/1cf52be26250fb8b320e4bdb80894a3d6bf0920f/exercises/practice/rational-numbers/rational-numbers.v#L7) currently shows the two argument names with the wrong ordering. We should fix line 7.

All 4 of the current community solutions { [autf](https://exercism.org/tracks/vlang/exercises/rational-numbers/solutions/autf), [david82](https://exercism.org/tracks/vlang/exercises/rational-numbers/solutions/david82), [metalim](https://exercism.org/tracks/vlang/exercises/rational-numbers/solutions/metalim), [keiraville](https://exercism.org/tracks/vlang/exercises/rational-numbers/solutions/keiraville) } show the correct ordering: numerator, denominator

In the example solution file [example.v](https://github.com/exercism/vlang/blob/1cf52be26250fb8b320e4bdb80894a3d6bf0920f/exercises/practice/rational-numbers/.meta/example.v#L44), we could replace `numerator` with `denominator` and replace `denominator` with `numerator`.

**Comment by 1ethanhansen** [comment]
Yep! I didn't catch that, thank you! Once someone makes a PR for this, it'll be an easy approve
