### ISSUE TITLE
misleading comment on exercises/practice/accumulate

### ISSUE THREAD

**Issue by alfu32** [exercism/vlang#70]
**first remark :** 
The exercise requires  the student to essentially re-implement `array.map`, why are the functions called accumulate ( that's an aggregation that in all programming languages that I know is called either reduce or fold ) while the requirement is to do something similar with map ( or transform in some languages )

**second remark:**

The reason "_Because V functions cannot be overloaded[1]_" comes across as misleading in the context of what the answers could be

```c
// Because V functions cannot be overloaded[1], make another function
//  called `accumulate_strs` that does the same thing for strings
// instead of ints

```
solutions:

```go

module main

// sol 1 with builtin map
fn accumulate_ints0(values []int, operation fn (int) int) []int {
	return values.map(operation)
}
fn accumulate_strs0(values []string, operation fn (string) string) []string {
	return values.map(operation)
}

// sol 2 reimplementation of builtin
fn accumulate_ints1(values []int, operation fn (int) int) []int {
	mut arr:=[]int{}
	for k in values {
		arr<<operation(k)
	}
	return arr
}
fn accumulate_strs1(values []string, operation fn (string) string) []string {
	mut arr:=[]string{}
	for k in values {
		arr<<operation(k)
	}
	return arr
}

// sol 3 generic reimplementation of builtin
fn  accumulate[T](values []T, operation fn(T) T) []T {
	mut arr:=[]T{}
	for k in values {
		arr<<operation(k)
	}
	return arr
}
fn accumulate_ints(values []int, operation fn (int) int) []int {
	return accumulate[int](values,operation)
}
fn accumulate_strs(values []string, operation fn (string) string) []string {
	return accumulate[string](values,operation)
}

// Because V functions cannot be overloaded[1], make another function
//  called `accumulate_strs` that does the same thing for strings
// instead of ints
```
what if it were possible to overload the accumulate_ints ? one would be able to overload the arguments, but not the return type :stuck_out_tongue: which does not apply because accumulate_str returns a []string that has little in common with []int in the context.

why don't you formulate like this :

```c
// Make another function
//  called `accumulate_strs` that does the same thing for strings
// instead of ints


```

**Comment by alfu32** [comment]
I apologize in advance for writing too much. :smile:

**Comment by 1ethanhansen** [comment]
Hi @alfu32 I've read your issue description multiple times and am still unclear: how exactly is the comment misleading? V does not allow for function overloading, but as you've shown in solution 3, it does allow for generic-typed functions. Here, rather than attempt to introduce the student to passing a function as an argument *and* generic-typed functions, I've elected to do only the former

If you have a way the comment might be misinterpreted, that would be helpful

**Comment by hraftery** [comment]
FWIW, I had the same reaction. I found the comment provided good guidance. I can't see how it would steer the student away from solutions like those you give, however only sol 2 meets the requirements, so I suppose I'm not sure a student would be on that path anyway. Was there a wrong turn you thought the comment might encourage?

Regarding the first remark, it might be better directed at the [problem specification](https://github.com/exercism/problem-specifications/tree/main/exercises/accumulate). You'll note your point has [already](https://github.com/exercism/problem-specifications/pull/1918) been raised and some action taken. Naming is hard, particularly when you need to not clash with anything in dozens of languages. I wonder if the name came from the notion of `collect()` in Java, which creates a collection by "accumulating". I'm not bothered by the name, but I can imagine the possibility of some confusion.

**Comment by 1ethanhansen** [comment]
@alfu32 pinging you here to see if this is still an issue you want to raise/have any more thoughts on

**Comment by alfu32** [comment]
I'll explain it again in fewer words : 

Take c++,JS, ts, java,go,kotlin and rust .... in all of these a transformation operation on a slice/array is called `map` or `transform`. `accummulate` does not do what transform does ( logically )

Also the fact that there's no function signature overloading is completly irrelevant.

The exercise is still there in it's original formulation despite having been merged in 2022 ... 

I'll just close the issue if you don't mind.
